make:
  urls_to_scan:
    - "https://www.uahirise.org/PDS/DTM/PSP/"
    - "https://www.uahirise.org/PDS/DTM/ESP/"
  samples: 100
  output: "data/dataset/v1/"
  tile_size: 512
  stride: 256
  batch_size: 500
  max_workers: 30

train:
  threads: 4
  batch_size: 8
  learning_rate: 0.00001
  epochs: 50
  weight_decay: 0.01
  w_l1: 0.6
  w_grad: 0.3
  w_ssim: 0.1
  local_data_dir: "data"

fill:
  selected_model: Intel/dpt-large
  tile_size: 512
  padding_size: 128
  model_path: "models/marsfill_model.pth"
  dataset_prefix: "dataset/v1"
  output_prefix: "filled"
  local_base_dir: "data"

hole_gen:
  holes: 10
  min_radius: 8
  max_radius: 16
  seed: 42
  nodata: -3.4028234663852886e38
