make:
  urls_to_scan:
    - "https://www.uahirise.org/PDS/DTM/PSP/"
    - "https://www.uahirise.org/PDS/DTM/ESP/"
  samples: 10
  output: "datasets"
  tile_size: 512
  stride: 256

train:
  threads: 4
  selected_model: Intel/dpt-large
  batch_size: 4
  learning_rate: 0.00001
  epochs: 50
  weight_decay: 0.01
  w_l1: 0.6
  w_grad: 0.3
  w_ssim: 0.1

fill:
  selected_model: Intel/dpt-large
  tile_size: 512
  padding_size: 128
  model_path: "outputs/marsfill_model.pth"
